# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WirelessAccessPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ssid', models.CharField(db_index=True, max_length=200)),
                ('bssid', macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17, null=True)),
                ('first_detection_time', models.DateTimeField()),
                ('last_detection_time', models.DateTimeField()),
                ('security', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WirelessAccessPointHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detection_time', models.DateTimeField()),
                ('rssi', models.IntegerField()),
                ('estimated_distance', models.FloatField()),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('height', models.FloatField()),
                ('access_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrive.WirelessAccessPoint')),
            ],
        ),
        migrations.CreateModel(
            name='WirelessClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_detection', models.DateTimeField()),
                ('last_detection', models.DateTimeField()),
                ('mac_address', macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WirelessProbeHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('probe_time', models.DateTimeField()),
                ('ssid', models.CharField(db_index=True, max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrive.WirelessClient')),
            ],
        ),
    ]
