# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wirelessaccesspoint',
            name='first_detection_method',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wirelessaccesspoint',
            name='last_detection_method',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
