# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wardrive', '0003_auto_20160629_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='WirelessAccessPointHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detection_time', models.DateTimeField()),
                ('rssi', models.IntegerField()),
                ('estimated_distance', models.FloatField()),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('height', models.FloatField()),
                ('access_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrive.WirelessAccessPoint')),
            ],
        ),
    ]
