# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrive', '0004_wirelessaccesspointhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('direction', models.CharField(max_length=200)),
                ('source_address', models.GenericIPAddressField()),
                ('destination_address', models.GenericIPAddressField()),
                ('payload', models.TextField()),
            ],
        ),
    ]
