# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrive', '0005_ftprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPCredential',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_address', models.GenericIPAddressField()),
                ('username', models.CharField(db_index=True, max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
