# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 04:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wardrive', '0006_ftpcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detection_time', models.DateTimeField()),
                ('status_code', models.IntegerField()),
                ('direction', models.CharField(max_length=200)),
                ('source_address', models.GenericIPAddressField()),
                ('destination_address', models.GenericIPAddressField()),
                ('payload', models.TextField()),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('method', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('host', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('server', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('headers', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='ftpcredential',
            name='detection_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 29, 4, 30, 1, 904765, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ftpcredential',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wardrive.FTPRequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ftprequest',
            name='detection_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 29, 4, 30, 11, 127472, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
