# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrive', '0007_auto_20160629_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPCredential',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detection_time', models.DateTimeField()),
                ('destination_address', models.GenericIPAddressField()),
                ('host', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(db_index=True, max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('authorization', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
