# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wardrive', '0008_httpcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detection_time', models.DateTimeField()),
                ('source_address', models.GenericIPAddressField()),
                ('source_mac_address', macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17, null=True)),
                ('destination_mac_address', macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17, null=True)),
                ('destination_address', models.GenericIPAddressField()),
                ('opcode', models.CharField(max_length=200)),
                ('qname', models.CharField(max_length=200)),
                ('qtype', models.CharField(max_length=200)),
                ('qclass', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ftprequest',
            name='destination_mac_address',
            field=macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='ftprequest',
            name='source_mac_address',
            field=macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='httprequest',
            name='destination_mac_address',
            field=macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='httprequest',
            name='source_mac_address',
            field=macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17, null=True),
        ),
    ]
