# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wardrive', '0009_auto_20160630_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelnetCredential',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detection_time', models.DateTimeField()),
                ('destination_address', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TelnetRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detection_time', models.DateTimeField()),
                ('source_address', models.GenericIPAddressField()),
                ('source_mac_address', macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17, null=True)),
                ('destination_mac_address', macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17, null=True)),
                ('destination_address', models.GenericIPAddressField()),
                ('payload', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ftpcredential',
            name='request',
        ),
    ]
