# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wardrive', '0010_auto_20160630_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelnetCommand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detection_time', models.DateTimeField()),
                ('source_address', models.GenericIPAddressField()),
                ('source_mac_address', macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17, null=True)),
                ('destination_mac_address', macaddress.fields.MACAddressField(blank=True, integer=False, max_length=17, null=True)),
                ('destination_address', models.GenericIPAddressField()),
                ('command', models.TextField()),
            ],
        ),
    ]
