# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrive', '0012_telnetcommand_command_raw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telnetcommand',
            name='command_raw',
        ),
    ]
